### ISSUE TITLE
The key for ROS Kinetic was updated

### ISSUE THREAD

**Issue by taohnouaccountb** [rlworkgroup/gym-sawyer#25]
https://github.com/rlworkgroup/gym-sawyer/blob/50759505617404d430350e3a561adbe0ffb9b2d1/docker/Dockerfile.ros_intera#L8

It seems ROS updated this key recently so it causes the following error:
`W: GPG error: http://packages.ros.org/ros/ubuntu xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F42ED6FBAB17C654
E: The repository 'http://packages.ros.org/ros/ubuntu xenial InRelease' is not signed.
ERROR: Service 'nvidia-ros-intera' failed to build: The command '/bin/sh -c apt -qy update &&   DEBIAN_FRONTEND=noninteractive apt -qy install     git-core     python-argparse     python-rosdep     python-rosinstall     python-vcstools     python-wstool     ros-kinetic-actionlib     ros-kinetic-actionlib-msgs     ros-kinetic-control-msgs     ros-kinetic-cv-bridge     ros-kinetic-desktop-full     ros-kinetic-dynamic-reconfigure     ros-kinetic-joystick-drivers     ros-kinetic-rospy-message-converter     ros-kinetic-rviz     ros-kinetic-tf2-ros     ros-kinetic-trajectory-msgs     ros-kinetic-xacro &&   apt-get clean &&   rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
Makefile:24: recipe for target 'build-nvidia-sawyer-sim' failed
make: *** [build-nvidia-sawyer-sim] Error 1
`

Suggested way to solve it could be replacing it with the new one from the [official installation guide](http://wiki.ros.org/kinetic/Installation/Ubuntu):
apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654

**Comment by ryanjulian** [comment]
@taohnouaccountb thanks for the report. Can you test your proposed fix and send a PR if it works?

**Comment by nalindas9** [comment]
It is not working even after updating the Key. PFA the screenshot of the error.
Could you suggest a way to deal with
![Screenshot from 2019-11-27 23-13-53](https://user-images.githubusercontent.com/44141068/69776782-9a880600-116b-11ea-8702-df096df2bb12.png)
 this?
Thanks!

**Comment by taohnouaccountb** [comment]
> It is not working even after updating the Key. PFA the screenshot of the error.
> Could you suggest a way to deal with this?
> ![Screenshot from 2019-11-27 23-13-53](https://user-images.githubusercontent.com/44141068/69776782-9a880600-116b-11ea-8702-df096df2bb12.png)
> 
> Thanks!

**Comment by taohnouaccountb** [comment]
> It is not working even after updating the Key. PFA the screenshot of the error.
> Could you suggest a way to deal with this?
> ![Screenshot from 2019-11-27 23-13-53](https://user-images.githubusercontent.com/44141068/69776782-9a880600-116b-11ea-8702-df096df2bb12.png)
> 
> Thanks!

Since you are building a docker image, updating the key in the host will not work.
If you are still having the problem, you may refer to PR #26 which should be able to fix it.
