### ISSUE TITLE
online training

### ISSUE THREAD

**Issue by MartinaRuocco** [rlworkgroup/gym-sawyer#27]
Hi :) it would be nice to have an alternative that allows online training, especially because during the pandemic there are a lot of students trying to work from home. 
So far, Mujoco is not compatible with it because of the machine-ID limitation. 
Do you think this is a feasible step for the future?

**Comment by ryanjulian** [comment]
@MartinaRuocco you can use MuJoCo either by installing locally (e.g. not using the Docker containers), or using a MuJoCo site license (if you have access to one -- they support virtual machines) with the Docker containers.

Unfortunately this is really out of our control, though I share your frustration with the MuJoCo licensing model.
